### ISSUE TITLE
SpringBoard crash on install app

### ISSUE THREAD

**Issue by Cadu171** [0xkuj/BackgrounderAction15AutoState#1]
When i try to install an app with spotlight, the springboard crashes.

iPhone 11
15.3.1
Dopamine

**Comment by 0xkuj** [comment]
please try version 1.0.1, I have fixed some crashes there
let me know if that worked out for you

**Comment by Cadu171** [comment]
worked, thank you 😄

**Comment by 0xkuj** [comment]
Thanks. Closing this issue
